version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - build_retry_count=0
      - execute_retry_count=0
      - build_retries=3
      - execute_retries=3
      - echo "run the next command"
  post_build:
    commands:
  build:
    commands:
