version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - retry_count=0
      - max_retries=(1,2,3)
      - for value in ${max_retries[@]};
         do
            echo $value;
         done
      - echo "run the next command"
      - npm install
      - zip -r TEST_NODE.zip *
  post_build:
    commands:
      - aws s3 cp TEST_NODE.zip s3://lambda-codebuild-sources/
      - aws lambda update-function-code --function-name TEST_NODE --s3-bucket lambda-codebuild-sources --s3-key TEST_NODE.zip
