version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - build_retry_count=0
      - execute_retry_count=0
      - build_retries=3
      - execute_retries=3
      - for ((build_retry_count=0; build_retry_count<build_retries; build_retry_count++)); do echo "Attempt build $build_retry_count"; npm install && break; done
      - echo "run the next command"
  post_build:
    commands:
  build:
    commands:
      - echo "Starting Docker build..."
      - docker build -t your-docker-image-name .
      - echo "Docker build completed."
