version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - retry_count=0
      - max_retries=3
      - while [ $retry_count -lt $max_retries ];
          do
            echo "Attempt  $retry_count";
            let "retry_count=retry_count+1"
        done
      - npm install
  post_build:
    commands:
