version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 254515880777.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t test_node .
      - echo "Tagging Docker image..."
      - docker tag test_node:latest 254515880777.dkr.ecr.us-east-1.amazonaws.com/test_node:latest
      - docker push 254515880777.dkr.ecr.us-east-1.amazonaws.com/test_node:latest
      - echo "docker pushed"
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - build_retry_count=0
      - execute_retry_count=0
      - build_retries=3
      - execute_retries=3
      - echo "run the next command"
  post_build:
    commands:
