version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - retry_count=0
      - max_retries=3
      - for ((retry_count=0; retry_count<max_retries; retry_count++)); do echo "Attempt  $retry_count"; if [ $retry_count -eq 1 ]; then break fi done
      - echo "run the next command"
  post_build:
    commands:
